"""
AFEM Investigation Reporting — Phase 5
========================================
Aggregates IntegrityReport (embedded in TimelineReport) + TimelineReport +
AttributionReport into one InvestigationReport, and renders it to JSON and
self-contained HTML.

Responsibility separation
--------------------------
build_investigation_report(...)   -> InvestigationReport   (pure aggregation)
render_investigation_html(...)    -> str                    (pure rendering)
write_investigation_json(...)     -> Path                    (pure persistence)
write_investigation_html(...)     -> Path                    (pure persistence)
generate_investigation_report(...) -> orchestrates the above four, nothing more

Non-negotiable invariants
--------------------------
* attribution_class, confidence_score, confidence_label, is_reliable,
  task_outcome, evidence_trust, reconstruction_completeness,
  authorization, observed_actions, unauthorized_actions,
  injection_assessment, injection_indicators, triggered_rules,
  confidence_contributions, uncertainty_reasons, supporting_evidence,
  contradictory_evidence are copied VERBATIM from AttributionReport.
  This module never recomputes, reinterprets, or overrides any of them.

* If an internal consistency check fails (e.g. evidence_trust says
  compromised but is_reliable is somehow True), the upstream value is
  preserved unchanged and a note is appended to reporting_warnings.
  Nothing here silently "fixes" upstream data.

* report_id, case_title, case_summary, investigator_findings,
  investigator_conclusion, limitations, and reporting_warnings are all
  deterministic - selected by fixed templates keyed on already-known
  upstream state, never generated by an LLM and never randomised.
  generated_at is the only field permitted to vary between runs.

Changes vs. the prior draft of this module
-------------------------------------------
* ``_atomic_write_text`` now cleans up its temp file on any failure
  (write, fsync, or replace) instead of leaving an orphaned ``*.tmpNNNN``
  file next to the destination. The temp filename also includes a
  short uuid suffix (not just the PID) so two writes to the same
  destination within one process cannot collide.
* HTML rendering of list-valued fields (authorized/prohibited/observed/
  unauthorized tools, tool sequence) now renders as an escaped
  comma-joined string instead of a Python list repr (`"['a', 'b']"`).
  This was a readability defect, not a security defect: the previous
  code always passed the value through ``str()`` before ``html.escape``,
  so no unescaped content could reach the page.
* Triggered-rule and confidence-contribution rows now also surface
  ``TriggeredRule.evidence_refs`` and ``RuleContribution.description``
  (previously silently dropped) so investigators are not missing
  fields that the Phase 4 schema actually populates.
* ``report_version`` is now passed explicitly rather than relying on
  the schema default, per the review requirement to confirm it is
  populated deterministically.
"""
from __future__ import annotations

import html
import json
import os
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Optional

from schemas.attribution import AttributionClass, AttributionReport, InjectionAssessment
from schemas.investigation import InvestigationReport
from schemas.report import TimelineReport

# ---------------------------------------------------------------------------
# Aggregation
# ---------------------------------------------------------------------------


def build_investigation_report(
    timeline_report:     TimelineReport,
    attribution_report:  AttributionReport,
    source_session_path: Optional[Path] = None,
) -> InvestigationReport:
    """
    Pure aggregation: combine Phase 3 + Phase 4 output into an
    InvestigationReport. Performs no file I/O and no analytical
    recomputation.

    Parameters
    ----------
    timeline_report :
        Phase 3 output. Its embedded ``integrity_report`` supplies all
        Phase 2 fields.
    attribution_report :
        Phase 4 output. Every attribution-related field on the returned
        InvestigationReport is copied verbatim from this object.
    source_session_path :
        Path to the original session JSONL, for provenance display.
        Relativised to the repository root when possible.

    Returns
    -------
    InvestigationReport
    """
    session_id = timeline_report.session_id
    ir = timeline_report.integrity_report  # embedded IntegrityReport, may be None defensively

    reporting_warnings: List[str] = []

    # --- Phase 2 fields (verbatim from embedded IntegrityReport) ---
    integrity_status  = getattr(ir, "verdict", "FAILED") if ir else "FAILED"
    session_complete  = getattr(ir, "session_complete", False) if ir else False
    genesis_hash      = getattr(ir, "genesis_hash", "") if ir else ""
    terminal_hash     = getattr(ir, "terminal_hash", "") if ir else ""
    verified_at       = getattr(ir, "verified_at", "") if ir else ""
    integrity_findings = list(getattr(ir, "findings", [])) if ir else []

    if ir is None:
        reporting_warnings.append(
            "TimelineReport.integrity_report was not available; integrity "
            "section fields default to their most conservative values."
        )

    # --- Consistency check (never corrects, only notes) ---
    ir_trust = getattr(ir, "evidence_trust", None) if ir else None
    ir_trust_value = getattr(ir_trust, "value", ir_trust) if ir_trust is not None else None
    if ir_trust_value is not None and ir_trust_value != attribution_report.evidence_trust:
        reporting_warnings.append(
            f"Evidence trust mismatch observed between IntegrityReport "
            f"('{ir_trust_value}') and AttributionReport "
            f"('{attribution_report.evidence_trust}'). AttributionReport's "
            f"value is preserved as authoritative; both are reported here "
            f"for investigator awareness."
        )

    # --- Phase 3 fields (verbatim from TimelineReport) ---
    user_prompt             = timeline_report.user_prompt
    timeline_entries        = list(timeline_report.entries)
    tool_sequence            = list(timeline_report.tool_sequence)
    reconstruction_anomalies = list(timeline_report.anomalies)

    # --- Phase 4 fields (verbatim from AttributionReport - never recomputed) ---
    attribution_class       = attribution_report.attribution_class
    confidence_score          = attribution_report.confidence_score
    confidence_label          = attribution_report.confidence_label
    reliable                  = attribution_report.is_reliable
    task_outcome               = attribution_report.task_outcome
    evidence_trust             = attribution_report.evidence_trust
    reconstruction_completeness = attribution_report.reconstruction_completeness
    authorization               = attribution_report.authorization
    observed_actions            = list(attribution_report.observed_actions)
    unauthorized_actions        = list(attribution_report.unauthorized_actions)
    injection_assessment        = attribution_report.injection_assessment
    injection_indicators        = list(attribution_report.injection_indicators)
    triggered_rules              = list(attribution_report.triggered_rules)
    confidence_contributions    = list(attribution_report.confidence_contributions)
    uncertainty_reasons          = list(attribution_report.uncertainty_reasons)
    supporting_evidence          = list(attribution_report.supporting_evidence)
    contradictory_evidence       = list(attribution_report.contradictory_evidence)

    # --- Phase 5 deterministic content ---
    report_id  = f"AFEM-INV-{session_id}"
    case_title = f"AFEM Investigation - {session_id}"
    case_summary = _build_case_summary(
        user_prompt, observed_actions, integrity_status, attribution_class, confidence_score,
    )
    investigator_findings = _build_investigator_findings(
        integrity_status, evidence_trust, unauthorized_actions,
        injection_assessment, injection_indicators,
    )
    investigator_conclusion = _build_conclusion(
        attribution_class, evidence_trust, injection_assessment,
    )
    limitations = _build_limitations(
        evidence_trust, reconstruction_completeness, reconstruction_anomalies,
        integrity_findings,
    )

    relativised_path = _relativise_path(source_session_path)

    return InvestigationReport(
        report_version=InvestigationReport.model_fields["report_version"].default,
        report_id=report_id,
        session_id=session_id,
        generated_at=datetime.now(timezone.utc).isoformat(),
        case_title=case_title,
        case_summary=case_summary,
        integrity_status=integrity_status,
        evidence_trust=evidence_trust,
        session_complete=session_complete,
        genesis_hash=genesis_hash,
        terminal_hash=terminal_hash,
        verified_at=verified_at,
        integrity_findings=integrity_findings,
        reconstruction_completeness=reconstruction_completeness,
        user_prompt=user_prompt,
        timeline=timeline_entries,
        tool_sequence=tool_sequence,
        reconstruction_anomalies=reconstruction_anomalies,
        attribution_class=attribution_class,
        confidence_score=confidence_score,
        confidence_label=confidence_label,
        reliable=reliable,
        task_outcome=task_outcome,
        authorization=authorization,
        observed_actions=observed_actions,
        unauthorized_actions=unauthorized_actions,
        injection_assessment=injection_assessment,
        injection_indicators=injection_indicators,
        triggered_rules=triggered_rules,
        confidence_contributions=confidence_contributions,
        uncertainty_reasons=uncertainty_reasons,
        supporting_evidence=supporting_evidence,
        contradictory_evidence=contradictory_evidence,
        investigator_findings=investigator_findings,
        investigator_conclusion=investigator_conclusion,
        limitations=limitations,
        reporting_warnings=reporting_warnings,
        source_session_path=relativised_path,
    )


# ---------------------------------------------------------------------------
# Deterministic template helpers (Phase 5 original content only)
# ---------------------------------------------------------------------------


def _relativise_path(path: Optional[Path]) -> str:
    """
    Return a repository-relative path string when possible, else a
    normalised absolute path string. Never fails report generation.
    """
    if path is None:
        return ""
    try:
        p = Path(path).resolve()
        cwd = Path.cwd().resolve()
        return str(p.relative_to(cwd))
    except (ValueError, OSError):
        return str(Path(path).as_posix())


def _build_case_summary(
    user_prompt:       Optional[str],
    observed_actions:  List[str],
    integrity_status:  str,
    attribution_class: AttributionClass,
    confidence_score:  float,
) -> str:
    prompt_text = user_prompt or "(no user prompt recorded)"
    cls = attribution_class.value if hasattr(attribution_class, "value") else str(attribution_class)
    actions_text = ", ".join(observed_actions) if observed_actions else "(none)"
    return (
        f"User request: \"{prompt_text}\". "
        f"Observed tool sequence: {actions_text}. "
        f"Integrity status: {integrity_status}. "
        f"Attribution: {cls} (confidence {confidence_score:.2f})."
    )


def _build_investigator_findings(
    integrity_status:      str,
    evidence_trust:         str,
    unauthorized_actions:    List[str],
    injection_assessment:    InjectionAssessment,
    injection_indicators:    list,
) -> List[str]:
    findings: List[str] = []

    findings.append(
        f"Evidence integrity status is {integrity_status}; "
        f"evidence trust is {evidence_trust.upper()}."
    )

    if unauthorized_actions:
        findings.append(
            f"Unauthorized actions observed: {', '.join(unauthorized_actions)}."
        )

    inj_value = injection_assessment.value if hasattr(injection_assessment, "value") else str(injection_assessment)
    if inj_value != "NONE":
        findings.append(
            f"{len(injection_indicators)} injection indicator(s) detected "
            f"in retrieved email content. Injection assessment: {inj_value}."
        )

    return findings


# Deterministic conclusion templates, keyed on AttributionClass.
_CONCLUSION_TEMPLATES = {
    AttributionClass.AUTH: (
        "The session evidence is intact and the reconstructed agent actions "
        "remained within the user-authorized scope."
    ),
    AttributionClass.SCOPE: (
        "The session evidence is intact. The agent performed one or more "
        "actions outside the user-authorized scope. No sufficient "
        "injection-to-action evidence was identified; the behavior is "
        "classified as a scope violation by the Phase 4 attribution engine."
    ),
    AttributionClass.INJ: (
        "The session evidence is intact. Instruction-like content was "
        "retrieved from external email content prior to unauthorized "
        "actions. The Phase 4 attribution engine classified the later "
        "actions as behaviorally correlated with the retrieved content."
    ),
    AttributionClass.AMBIG: (
        "The available evidence is insufficient or unreliable for a "
        "definitive attribution, per the Phase 4 attribution engine's "
        "trust-aware gating."
    ),
}

_RESISTED_INJECTION_TEMPLATE = (
    "The session evidence is intact. Instruction-like content was observed "
    "in retrieved external email content, but the Phase 4 attribution "
    "engine found no matching unauthorized action. The observed agent "
    "behavior remained within the user-authorized scope."
)


def _build_conclusion(
    attribution_class:    AttributionClass,
    evidence_trust:        str,
    injection_assessment:  InjectionAssessment,
) -> str:
    """
    Select a deterministic conclusion template. Never overrides
    attribution_class; only chooses which fixed sentence to display for
    the class the Phase 4 engine already selected.
    """
    inj_value = injection_assessment.value if hasattr(injection_assessment, "value") else str(injection_assessment)

    if attribution_class == AttributionClass.AUTH and inj_value == "ATTEMPT_DETECTED":
        return _RESISTED_INJECTION_TEMPLATE

    base = _CONCLUSION_TEMPLATES[attribution_class]

    if evidence_trust == "compromised":
        base += (
            " Evidence trust is COMPROMISED; this conclusion is qualified "
            "and should not be relied upon without further investigation."
        )

    return base


def _build_limitations(
    evidence_trust:              str,
    reconstruction_completeness: str,
    reconstruction_anomalies:     List[str],
    integrity_findings:            list,
) -> List[str]:
    limitations: List[str] = []

    if evidence_trust == "compromised":
        limitations.append(
            "Evidence trust is COMPROMISED. One or more events failed "
            "integrity verification. Conclusions drawn from this session "
            "carry materially reduced reliability."
        )
    elif evidence_trust == "degraded":
        limitations.append(
            "Evidence trust is DEGRADED. Structural anomalies were present "
            "in the session evidence."
        )
    elif evidence_trust == "unknown":
        limitations.append(
            "Evidence trust could not be determined."
        )

    if reconstruction_completeness != "complete":
        limitations.append(
            f"Timeline reconstruction completeness is "
            f"{reconstruction_completeness.upper()}; some session activity "
            f"may not be represented in the reconstructed timeline."
        )

    if reconstruction_anomalies:
        limitations.append(
            f"{len(reconstruction_anomalies)} reconstruction anomaly(ies) "
            f"were detected during timeline reconstruction."
        )

    if integrity_findings:
        limitations.append(
            f"{len(integrity_findings)} integrity finding(s) were recorded "
            f"during evidence verification."
        )

    return limitations


# ---------------------------------------------------------------------------
# HTML rendering
# ---------------------------------------------------------------------------


def _escape(value: object) -> str:
    """Centralised escaping helper. Every dynamic HTML value passes through this."""
    return html.escape(str(value), quote=True)


def _escape_list(items: List[str], empty: str = "(none)") -> str:
    """Render a list of strings as an escaped, comma-joined string."""
    if not items:
        return html.escape(empty, quote=True)
    return html.escape(", ".join(str(i) for i in items), quote=True)


def render_investigation_html(report: InvestigationReport) -> str:
    """
    Pure rendering: produce a self-contained, static, dependency-free HTML
    string from an already-built InvestigationReport. Performs no analysis
    and no file I/O.
    """
    e = _escape

    def _rows(items: List[str], empty: str = "(none)") -> str:
        if not items:
            return f"<p class='muted'>{e(empty)}</p>"
        return "<ul>" + "".join(f"<li>{e(i)}</li>" for i in items) + "</ul>"

    def _timeline_rows() -> str:
        if not report.timeline:
            return "<p class='muted'>(no timeline entries)</p>"
        rows = []
        for entry in report.timeline:
            refs = "; ".join(
                f"{e(r.get('artifact_type','?'))}:{e(r.get('artifact_id','?'))}"
                for r in (entry.artifact_refs or [])
            ) or "(none)"
            rows.append(
                "<tr>"
                f"<td>{e(entry.sequence_number)}</td>"
                f"<td>{e(entry.timestamp or '')}</td>"
                f"<td>{e(entry.actor)}</td>"
                f"<td>{e(entry.event_type)}</td>"
                f"<td>{e(entry.tool_name or '')}</td>"
                f"<td>{e(entry.action)}</td>"
                f"<td>{e(entry.input_summary or '')}</td>"
                f"<td>{e(entry.output_summary or '')}</td>"
                f"<td>{refs}</td>"
                f"<td>{e(entry.integrity_status)}</td>"
                f"<td>{e(entry.anomaly or '')}</td>"
                "</tr>"
            )
        return (
            "<table><thead><tr>"
            "<th>Seq</th><th>Timestamp</th><th>Actor</th><th>Type</th>"
            "<th>Tool</th><th>Action</th><th>Input</th><th>Output</th>"
            "<th>Artifacts</th><th>Integrity</th><th>Anomaly</th>"
            "</tr></thead><tbody>" + "".join(rows) + "</tbody></table>"
        )

    def _findings_rows() -> str:
        if not report.integrity_findings:
            return "<p class='muted'>(no integrity findings)</p>"
        rows = []
        for f in report.integrity_findings:
            ftype = getattr(f.finding_type, "value", f.finding_type) if f.finding_type else ""
            sev   = getattr(f.severity, "value", f.severity) if f.severity else ""
            rows.append(
                f"<li><strong>{e(sev).upper()}</strong> - {e(ftype)} "
                f"(seq {e(f.affected_sequence)}): {e(f.message)}</li>"
            )
        return "<ul>" + "".join(rows) + "</ul>"

    def _rules_rows() -> str:
        if not report.triggered_rules:
            return "<p class='muted'>(no rules triggered)</p>"
        rows = []
        for r in report.triggered_rules:
            refs_text = ""
            if r.evidence_refs:
                refs_text = " <span class='muted'>[refs: seq " + ", ".join(
                    e(ref.timeline_sequence) for ref in r.evidence_refs
                ) + "]</span>"
            rows.append(
                f"<li><strong>{e(r.rule_id)}</strong>: {e(r.description)} "
                f"&rarr; {e(r.outcome)}{refs_text}</li>"
            )
        return "<ul>" + "".join(rows) + "</ul>"

    def _confidence_rows() -> str:
        if not report.confidence_contributions:
            return "<p class='muted'>(no confidence contributions)</p>"
        rows = []
        for c in report.confidence_contributions:
            sign = "+" if c.delta >= 0 else ""
            rows.append(
                f"<li><strong>{e(c.rule_id)}</strong> {sign}{e(f'{c.delta:.2f}')} "
                f"- {e(c.description)}: {e(c.reason)}</li>"
            )
        return "<ul>" + "".join(rows) + "</ul>"

    def _injection_rows() -> str:
        if not report.injection_indicators:
            return "<p class='muted'>(no injection indicators detected)</p>"
        rows = []
        for ind in report.injection_indicators:
            rows.append(
                f"<li><strong>{e(ind.category)}</strong> matched "
                f"'{e(ind.phrase)}' (tool: {e(ind.tool_name)}, "
                f"seq: {e(ind.timeline_sequence)})"
                + (f"<br><span class='muted'>excerpt: {e(ind.content_excerpt)}</span>" if ind.content_excerpt else "")
                + "</li>"
            )
        return "<ul>" + "".join(rows) + "</ul>"

    def _evidence_refs(refs: list) -> str:
        if not refs:
            return "<p class='muted'>(none)</p>"
        rows = []
        for r in refs:
            rows.append(
                f"<li>seq {e(r.timeline_sequence)} - {e(r.event_type)} "
                f"({e(r.tool_name or '')}) - {e(r.reason)} "
                f"[integrity: {e(r.integrity_status)}]</li>"
            )
        return "<ul>" + "".join(rows) + "</ul>"

    trust_class = {
        "trusted": "ok", "degraded": "warn", "compromised": "bad", "unknown": "bad",
    }.get(report.evidence_trust, "warn")

    attribution_class_val = getattr(report.attribution_class, 'value', report.attribution_class)
    confidence_label_val = getattr(report.confidence_label, 'value', report.confidence_label)
    task_outcome_val = getattr(report.task_outcome, 'value', report.task_outcome)
    injection_assessment_val = getattr(report.injection_assessment, 'value', report.injection_assessment)

    html_doc = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>{e(report.case_title)}</title>
<style>
  body {{ font-family: -apple-system, Segoe UI, Arial, sans-serif; margin: 2em; color: #1a1a1a; background: #fff; }}
  h1 {{ font-size: 1.6em; border-bottom: 2px solid #333; padding-bottom: 0.3em; }}
  h2 {{ font-size: 1.2em; margin-top: 1.6em; border-bottom: 1px solid #ccc; padding-bottom: 0.2em; }}
  table {{ border-collapse: collapse; width: 100%; font-size: 0.85em; margin-top: 0.5em; }}
  th, td {{ border: 1px solid #ccc; padding: 4px 8px; text-align: left; vertical-align: top; }}
  th {{ background: #f0f0f0; }}
  .muted {{ color: #777; font-style: italic; }}
  .badge {{ display: inline-block; padding: 2px 10px; border-radius: 4px; font-weight: bold; color: #fff; }}
  .ok {{ background: #2e7d32; }}
  .warn {{ background: #b8860b; }}
  .bad {{ background: #b00020; }}
  .grid {{ display: grid; grid-template-columns: 220px 1fr; gap: 4px 12px; max-width: 700px; }}
  .grid div:nth-child(odd) {{ font-weight: bold; }}
  ul {{ margin: 0.3em 0; padding-left: 1.4em; }}
  .conclusion {{ padding: 1em; border-left: 4px solid #333; background: #f7f7f7; }}
  @media print {{ body {{ margin: 0.5em; }} }}
</style>
</head>
<body>
<h1>{e(report.case_title)}</h1>
<p><strong>Report ID:</strong> {e(report.report_id)} &nbsp; <strong>Generated:</strong> {e(report.generated_at)} &nbsp; <strong>Schema:</strong> v{e(report.report_version)}</p>
<p>{e(report.case_summary)}</p>

<h2>Evidence Integrity</h2>
<div class="grid">
  <div>Integrity Status</div><div>{e(report.integrity_status)}</div>
  <div>Evidence Trust</div><div><span class="badge {trust_class}">{e(report.evidence_trust.upper())}</span></div>
  <div>Session Complete</div><div>{e(report.session_complete)}</div>
  <div>Genesis Hash</div><div><code>{e(report.genesis_hash)}</code></div>
  <div>Terminal Hash</div><div><code>{e(report.terminal_hash)}</code></div>
  <div>Verified At</div><div>{e(report.verified_at)}</div>
</div>
<h3>Integrity Findings</h3>
{_findings_rows()}

<h2>Reconstruction</h2>
<div class="grid">
  <div>Completeness</div><div>{e(report.reconstruction_completeness.upper())}</div>
  <div>User Prompt</div><div>{e(report.user_prompt or '(none)')}</div>
  <div>Source Session</div><div><code>{e(report.source_session_path)}</code></div>
</div>
<h3>Reconstruction Anomalies</h3>
{_rows(report.reconstruction_anomalies)}
<h3>Timeline</h3>
{_timeline_rows()}

<h2>Attribution</h2>
<div class="grid">
  <div>Attribution Class</div><div><strong>{e(attribution_class_val)}</strong></div>
  <div>Confidence Score</div><div>{e(f'{report.confidence_score:.2f}')}</div>
  <div>Confidence Label</div><div>{e(confidence_label_val)}</div>
  <div>Reliable</div><div><span class="badge {'ok' if report.reliable else 'bad'}">{e('Yes' if report.reliable else 'No')}</span></div>
  <div>Task Outcome</div><div>{e(task_outcome_val)}</div>
</div>

<h3>Authorization</h3>
<div class="grid">
  <div>Authorized Tools</div><div>{_escape_list(report.authorization.authorized_tools)}</div>
  <div>Prohibited Tools</div><div>{_escape_list(report.authorization.prohibited_tools)}</div>
  <div>Observed Actions</div><div>{_escape_list(report.observed_actions)}</div>
  <div>Unauthorized Actions</div><div>{_escape_list(report.unauthorized_actions)}</div>
</div>
{_rows(report.authorization.notes, empty="(no authorization notes)")}

<h3>Injection Assessment: {e(injection_assessment_val)}</h3>
{_injection_rows()}

<h3>Triggered Rules</h3>
{_rules_rows()}

<h3>Confidence Contributions</h3>
{_confidence_rows()}

<h3>Supporting Evidence</h3>
{_evidence_refs(report.supporting_evidence)}

<h3>Contradictory Evidence</h3>
{_evidence_refs(report.contradictory_evidence)}

<h3>Uncertainty Reasons</h3>
{_rows(report.uncertainty_reasons)}

<h2>Investigator Findings</h2>
{_rows(report.investigator_findings)}

<h2>Conclusion</h2>
<div class="conclusion">{e(report.investigator_conclusion)}</div>

<h2>Limitations</h2>
{_rows(report.limitations)}

<h2>Reporting Warnings</h2>
{_rows(report.reporting_warnings, empty="(no warnings)")}

</body>
</html>
"""
    return html_doc


# ---------------------------------------------------------------------------
# Safe persistence (atomic write via temp file + Path.replace)
# ---------------------------------------------------------------------------


def _atomic_write_text(path: Path, content: str) -> None:
    """
    Write text to path atomically: write to a temp sibling, flush, close,
    then Path.replace(). Works on Windows and POSIX; no third-party
    dependency required.

    On any failure (write, fsync, or replace) the temp file is removed
    before the exception propagates, so a failed report generation never
    leaves an orphaned ``*.tmp*`` file next to the destination.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp_path = path.with_suffix(
        path.suffix + f".tmp{os.getpid()}{uuid.uuid4().hex[:8]}"
    )
    try:
        with open(tmp_path, "w", encoding="utf-8") as fh:
            fh.write(content)
            fh.flush()
            os.fsync(fh.fileno())
        tmp_path.replace(path)
    except BaseException:
        if tmp_path.exists():
            try:
                tmp_path.unlink()
            except OSError:
                pass
        raise


def write_investigation_json(report: InvestigationReport, output_dir: Path) -> Path:
    """
    Persist the authoritative JSON investigation report.

    Uses ``report.model_dump(mode="json")`` so every enum serializes to its
    plain string value, then ``json.dump`` with deterministic formatting.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / f"{report.session_id}_investigation.json"
    data = report.model_dump(mode="json")
    content = json.dumps(data, ensure_ascii=False, indent=2)
    _atomic_write_text(path, content)
    return path


def write_investigation_html(report: InvestigationReport, output_dir: Path) -> Path:
    """Render and persist the self-contained HTML investigation report."""
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / f"{report.session_id}_investigation.html"
    content = render_investigation_html(report)
    _atomic_write_text(path, content)
    return path


# ---------------------------------------------------------------------------
# Convenience orchestration (delegates only - no logic of its own)
# ---------------------------------------------------------------------------


def generate_investigation_report(
    timeline_report:     TimelineReport,
    attribution_report:  AttributionReport,
    output_dir:           Path,
    source_session_path:  Optional[Path] = None,
    write_html:            bool = True,
):
    """
    Convenience wrapper delegating to build_investigation_report(),
    write_investigation_json(), and optionally write_investigation_html().
    Contains no aggregation or rendering logic itself.

    Returns
    -------
    (InvestigationReport, json_path, html_path_or_None)
    """
    report = build_investigation_report(
        timeline_report, attribution_report, source_session_path,
    )
    json_path = write_investigation_json(report, output_dir)
    html_path = write_investigation_html(report, output_dir) if write_html else None
    return report, json_path, html_path