"""
AFEM Investigation Schemas — Phase 5: Forensic Investigation Reporting
========================================================================
Pydantic model for the final investigation report.

Design principle
-----------------
InvestigationReport is a pure aggregation of Phase 2 (IntegrityReport),
Phase 3 (TimelineReport), and Phase 4 (AttributionReport) output. It embeds
existing typed models directly wherever possible - TimelineEntry,
AuthorizationAssessment, InjectionIndicator, TriggeredRule, RuleContribution,
EvidenceReference, ForensicFinding - rather than reducing them to untyped
dicts. This preserves the existing Pydantic validation and forensic data
contracts of every upstream phase.

Only genuinely new Phase 5 content (investigator_findings,
investigator_conclusion, limitations, reporting_warnings) uses plain str
fields, because that content originates in Phase 5 itself and has no
upstream typed representation to preserve.

Attribution fields (attribution_class, confidence_score, confidence_label,
reliable, task_outcome, injection_assessment) are copied verbatim from the
existing AttributionReport and are never recomputed, reinterpreted, or
overridden by this schema or by reporting/investigation.py. The Phase 4
engine remains the sole authority for attribution and trust-aware gating.

Circular-import check
----------------------
This module imports from schemas.report, schemas.attribution, and
schemas.integrity directly. None of those three modules import from
schemas.investigation, and this module never imports the schemas package
itself - only its submodules. No import cycle exists.

Serialization
-------------
All enum-typed fields (attribution_class, confidence_label, task_outcome,
injection_assessment) serialize correctly under
InvestigationReport.model_dump(mode="json") regardless of the source
model's use_enum_values configuration - pydantic v2 normalizes enums to
their .value at dump time in "json" mode. reporting/investigation.py
must always use mode="json" when producing the authoritative JSON file.
"""
from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field

from schemas.attribution import (
    AttributionClass,
    AuthorizationAssessment,
    ConfidenceLabel,
    EvidenceReference,
    InjectionAssessment,
    InjectionIndicator,
    RuleContribution,
    TaskOutcome,
    TriggeredRule,
)
from schemas.integrity import ForensicFinding
from schemas.report import TimelineEntry


class InvestigationReport(BaseModel):
    """
    Complete Phase 5 output. Correlates IntegrityReport + TimelineReport +
    AttributionReport into one investigator-facing document.

    Every Phase 2/3/4 field here is a direct, unmodified copy from the
    corresponding upstream report. Only the four fields under
    "Phase 5 - new content" are generated by this phase, and all four are
    produced by deterministic template selection - never free-text
    generation and never a re-derivation of attribution logic.
    """

    report_version: str = "1.0"
    report_id:       str = Field(
        ..., description="Deterministic identifier: 'AFEM-INV-<session_id>'."
    )
    session_id:      str
    generated_at:    str = Field(
        ..., description="ISO-8601 UTC timestamp. The only non-deterministic field."
    )

    case_title:   str
    case_summary: str

    # --- Phase 2 (verbatim from IntegrityReport) ---
    integrity_status:   str = Field(..., description="ir.verdict - 'VERIFIED' | 'FAILED'.")
    evidence_trust:     str = Field(..., description="Copied from AttributionReport.evidence_trust.")
    session_complete:   bool
    genesis_hash:        str = ""
    terminal_hash:       str = ""
    verified_at:          str = ""
    integrity_findings:   List[ForensicFinding] = Field(default_factory=list)

    # --- Phase 3 (verbatim from TimelineReport) ---
    reconstruction_completeness: str = Field(
        ..., description="Copied from AttributionReport.reconstruction_completeness."
    )
    user_prompt:              Optional[str] = None
    timeline:                 List[TimelineEntry] = Field(default_factory=list)
    tool_sequence:             List[str]           = Field(default_factory=list)
    reconstruction_anomalies: List[str]           = Field(default_factory=list)

    # --- Phase 4 (verbatim from AttributionReport - never recomputed) ---
    attribution_class:         AttributionClass
    confidence_score:          float = Field(..., ge=0.0, le=1.0)
    confidence_label:          ConfidenceLabel
    reliable:                  bool = Field(
        ..., description="Copied verbatim from AttributionReport.is_reliable. Never recomputed here."
    )
    task_outcome:               TaskOutcome
    authorization:              AuthorizationAssessment
    observed_actions:           List[str] = Field(default_factory=list)
    unauthorized_actions:       List[str] = Field(default_factory=list)
    injection_assessment:       InjectionAssessment
    injection_indicators:       List[InjectionIndicator]  = Field(default_factory=list)
    triggered_rules:            List[TriggeredRule]        = Field(default_factory=list)
    confidence_contributions:   List[RuleContribution]     = Field(default_factory=list)
    uncertainty_reasons:        List[str]                  = Field(default_factory=list)
    supporting_evidence:        List[EvidenceReference]    = Field(default_factory=list)
    contradictory_evidence:     List[EvidenceReference]    = Field(default_factory=list)

    # --- Phase 5 - new content (deterministic, template-derived only) ---
    investigator_findings:    List[str] = Field(
        default_factory=list,
        description="Deterministic, condition-gated findings. Never LLM-generated.",
    )
    investigator_conclusion:  str = Field(
        ..., description="Deterministic templated narrative selected by attribution_class + evidence state."
    )
    limitations:               List[str] = Field(
        default_factory=list,
        description="Explicit statements of evidence-quality or reconstruction limitations.",
    )
    reporting_warnings:        List[str] = Field(
        default_factory=list,
        description=(
            "Reserved for cases where Phase 5 detects an internal inconsistency "
            "in upstream data (e.g. evidence_trust/reliable mismatch). Phase 5 "
            "never changes the upstream value in response - it only records "
            "the observation here for investigator awareness."
        ),
    )

    source_session_path: str = ""