"""
AFEM Evidence Collector
=======================
Writes structured forensic events to ``data/evidence/evidence.jsonl``.

Responsibilities
----------------
* Assign a monotonically increasing ``sequence_number`` to each event within
  a session. This is the primary ordering signal used by Phase 2 integrity
  verification — it is not derived from timestamps, which can collide.
* Serialise each event to a single JSON line and flush immediately, so the
  file is always readable even if the process crashes mid-session.
* Provide one clearly named method per event type, so call sites in
  ``agent/langgraph_agent.py`` are self-documenting.

Thread safety
-------------
A ``threading.Lock`` guards the counter increment and the file write together
as a single atomic operation. LangGraph may parallelise tool calls in future
versions; the lock ensures sequence numbers remain unique and ordered.

Dependency direction
--------------------
``EvidenceCollector`` imports from ``schemas`` and ``config`` only.
It has no knowledge of LangGraph, the email tools, or the database.
This means Phases 2–5 can instantiate a collector independently of the agent.

Usage
-----
    from collector import EvidenceCollector

    collector = EvidenceCollector(session_id="abc-123")
    collector.log_session_start(user_prompt="...", model="...")
    collector.log_tool_call(tool_name="search_email", input_data={...})
    collector.log_tool_result(tool_name="search_email", output_data=[...])
    collector.log_agent_response(content="Here are the results...")
    collector.log_session_end()
"""
from __future__ import annotations

import logging
import threading
from pathlib import Path
from typing import Any, Optional
from integrity.sealer import SealingError, seal_session

from config import EVIDENCE_DIR
from schemas import (
    AgentResponseEvent,
    SessionEndEvent,
    SessionStartEvent,
    ToolCallEvent,
    ToolName,
    ToolResultEvent,
    UserPromptEvent,
)

logger = logging.getLogger(__name__)


class EvidenceCollector:
    """
    Append-only, thread-safe forensic event writer.

    One instance is created per agent session. The ``session_id`` is stamped
    on every event so that multiple sessions can share a single
    ``evidence.jsonl`` file and be distinguished by readers.

    Parameters
    ----------
    session_id :
        UUID string identifying this session. Generated by ``run_agent()``
        if not supplied by the caller.
    output_path :
        Path to the JSONL evidence file. Defaults to EVIDENCE_DIR
        so tests can override it with a temporary path.
    """

    def __init__(
        self,
        session_id: str,
        output_path: Path | None = None,
        auto_seal: bool = True,
    ) -> None:
        self.session_id = session_id

        if output_path is None:
            output_path = EVIDENCE_DIR / f"{session_id}.jsonl"

        self.output_path = output_path
        self.auto_seal = auto_seal

        self._lock = threading.Lock()
        self._seq = 0

        self.output_path.parent.mkdir(parents=True, exist_ok=True)

        logger.info(
            "EvidenceCollector ready. session=%s file=%s auto_seal=%s",
            self.session_id,
            self.output_path,
            self.auto_seal,
        )

    # ------------------------------------------------------------------
    # Public logging methods — one per event type
    # ------------------------------------------------------------------

    def log_session_start(self, user_prompt: str, model: str) -> None:
        """Log the session-start metadata event."""
        self._write(SessionStartEvent(
            session_id=self.session_id,
            user_prompt=user_prompt,
            model=model,
        ))

    def log_user_prompt(self, content: str) -> None:
        """Log the raw user prompt as the first substantive evidence event."""
        self._write(UserPromptEvent(
            session_id=self.session_id,
            content=content,
        ))

    def log_tool_call(self, tool_name: str, input_data: dict[str, Any]) -> None:
        """
        Log the agent's intent to call a tool.

        ``tool_name`` is coerced to ``ToolName`` here so that any
        unrecognised tool name raises a ``ValueError`` at the collector
        boundary rather than silently writing an invalid event to the
        evidence file.
        """
        self._write(ToolCallEvent(
            session_id=self.session_id,
            tool_name=ToolName(tool_name),
            input_data=input_data,
        ))

    def log_tool_result(
        self,
        tool_name: str,
        output_data: Any,
        error: Optional[str] = None,
        row_count: Optional[int] = None,
    ) -> None:
        """Log the outcome of a tool call."""
        self._write(ToolResultEvent(
            session_id=self.session_id,
            tool_name=ToolName(tool_name),
            output_data=output_data,
            error=error,
            row_count=row_count,
        ))

    def log_agent_response(self, content: str) -> None:
        """Log the agent's final natural-language response."""
        self._write(AgentResponseEvent(
            session_id=self.session_id,
            content=content,
        ))

    def log_session_end(self, status: str = "completed") -> None:
        """
        Log the session-end event and close the sequence.

        ``total_events`` is the count of events logged *before* this call,
        so a reader can detect a truncated file by comparing line count to
        this value.
        """
        # Capture count before the end event is written.
        events_before_end = self._seq
        self._write(SessionEndEvent(
            session_id=self.session_id,
            total_events=events_before_end,
            status=status,
        ))
        logger.info(
            "Session ended.  session=%s  total_events=%d  status=%s",
            self.session_id,
            events_before_end,
            status,
        )
        if self.auto_seal:
            try:
                seal_session(self.output_path)
            except SealingError as exc:
                logger.error(
                    "Failed to seal evidence session %s: %s",
                    self.session_id,
                    exc,
                )
    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _write(self, event: Any) -> None:
        """
        Set the sequence number, serialise the event, and append it to the
        JSONL file. The lock makes the counter increment and the file write
        a single atomic operation.
        """
        with self._lock:
            event.sequence_number = self._seq
            self._seq += 1
            line = event.to_jsonl()
            with open(self.output_path, "a", encoding="utf-8") as fh:
                fh.write(line + "\n")
                fh.flush()

        logger.debug(
            "Event written.  type=%s  seq=%d",
            event.event_type,
            event.sequence_number,
        )